### ISSUE TITLE
Modify timing information in CSV/JSON output (PR #98)

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#107]
For some processing it is useful to have information on absolute time of benchmark repetitions (start + end), for example to see how much time is spent between repetitions (GC or validation), or to correlate with events reported by the VM (GC log, JIT log), which have timestamps measured since VM start. I would suggest the following modifications:

- At the start of the harness, acquire delta between System.nanoTime and VM start as reported by java.lang.Runtime MX bean (= nanoStartTime).
- For each benchmark repetition, report time when the repetition started relative to VM start (nanoTime-nanoStartTime) and repetition duration (as reported now).
- In JSON, and in comments in CSV header, include information on VM start as ISO UTC timestamp (to permit correlation with external logs).

**Comment by ceresek** [comment]
@lbulej I was thinking a bit about data size - the VM start thing is a constant that would be repeated after each iteration, so a bit of a waste (easily compressed of course).

**Comment by vhotspur** [comment]
@ceresek Seems to me that this was fixed via #216 and #218. Can we close this?
