### ISSUE TITLE
Website Completion

### ISSUE THREAD

**Issue by axel22** [renaissance-benchmarks/renaissance#11]
The website is mostly ready, but it is still missing a few things:

- ~~JavaScript logic that fetches the README.md and CONTRIBUTION.md and embeds the content into a special page on the website (so that the files and the website are always in sync) - Contribute link at the top is already there, Getting Started link also (should lead to a page with the README)~~
- ~~The link to the **downloads** page~~
- Link to the Travis builds is there, but we should check if the link and the badge work
- Link to the latest and historical benchmark results - we need an extra page for this
- ~~Link to the ScalaDoc/JavaDoc of the Renaissance API~~
- ~~Link to the download page~~
- Link to a discussion forum - either Gitter or something else (Discuss at the top)

**Comment by farquet** [comment]
Can this be closed ?

**Comment by axel22** [comment]
Yes, we can close.
