### ISSUE TITLE
JMH support

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#120]
The suite should provide support for [OpenJDK JMH](https://openjdk.java.net/projects/code-tools/jmh/).

**Comment by ceresek** [comment]
Could you please elaborate what such support would look like ? Making the `runIteration` method into something that JMH executes in a separate JVM instance and then collect the results, or ... ?

**Comment by axel22** [comment]
I think that we should have a separate build target in `build.sbt` that knows how to bundle a JMH-compliant JAR. There is an sbt plugin that knows how to detect JMH wrapper classes and do that. The only thing that our `build.sbt` task should be capable of doing is generating those JMH wrappers.

**Comment by plokhotnyuk** [comment]
@axel22 could it be done with [sbt-jmh](https://github.com/ktoso/sbt-jmh)?

**Comment by axel22** [comment]
> @axel22 could it be done with [sbt-jmh](https://github.com/ktoso/sbt-jmh)?

Yes, exactly - that's the one I was referring to! I think it should work quite well.

**Comment by axel22** [comment]
@lbulej @vhotspur 
I plan to dedicate some time into implementing this.
My plan is to add an additional subproject that is capable of producing a JMH jar. I don't think this should conflict with the API redesign (https://github.com/renaissance-benchmarks/renaissance/issues/81), but still wanted to give you a heads-up first!

**Comment by lbulej** [comment]
Fine with me, let's see how that goes.

**Comment by axel22** [comment]
Closed with: https://github.com/renaissance-benchmarks/renaissance/pull/154
