### ISSUE TITLE
Version is "?.?.?" (incorrectly reading the manifest on JDK8)

### ISSUE THREAD

**Issue by villazon** [renaissance-benchmarks/renaissance#123]
This issue seems to be a problem in `MetaInfo.java` when reading the `"/META-INF/MANIFEST.MF"`

On macOS, with JDK 8, the version is print as `?.?.?`, whereas with JDK 9, it prints the version correctly. 

When trying to print all the attributes as follows:
```
      Attributes mainAttributes = manifest.getMainAttributes();
      for (Iterator it = mainAttributes.keySet().iterator(); it.hasNext();) {
        Attributes.Name attrName = (Attributes.Name) it.next();
        String attrValue = mainAttributes.getValue(attrName);
        System.out.println(attrName + " : " + attrValue);
      }
```
on JDK 8, only two attributes are printed:

```
Created-By : 1.4.2_09 (Apple Computer, Inc.)
Manifest-Version : 1.0
```
and therefore reading ` mainAttributes.getValue("Renaissance-Version")` fails. Note that "Created-By" is **not** in the manifest!

On JDK 9, all the attributes from the manifest file are read correctly.

**Comment by vhotspur** [comment]
@villazon Would you please paste here the contents of the `MANIFEST.MF` (as found in the super JAR)? Because it seems to me that SBT does not generate it properly...

**Comment by villazon** [comment]
This is the content:
```bash
$ jar xvf target/renaissance-0.9.0.jar META-INF/MANIFEST.MF
 inflated: META-INF/MANIFEST.MF
$ more META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: renaissance
Implementation-Version: 0.9.0
Specification-Vendor: org.renaissance
Specification-Title: renaissance
Implementation-Vendor-Id: org.renaissance
Renaissance-Version: 0.9.0
Specification-Version: 0.9.0
Main-Class: org.renaissance.Launcher
Implementation-Vendor: org.renaissance

```

Note that there is an empty line at the end.

**Comment by villazon** [comment]
On linux with JDK 8, it works fine. I seems to be a problem with macOS...

**Comment by villazon** [comment]
This issue seems to be similar to this bug in OpenJDK 8 https://bugs.openjdk.java.net/browse/JDK-8201636

I was able to reproduce it. I downloaded the `JI9053398.jar` file and run it:

```bash
$ java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
$ java -jar JI9053398.jar 
null
```
and with JDK9, it works
```bash
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
$ java -jar JI9053398.jar 
Main job catol 
```

It seems to be a problem to read the manifest in JDK8.

**Comment by villazon** [comment]
It could be related to classloading... 

https://bugs.openjdk.java.net/browse/JDK-8193522?focusedCommentId=14144614&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14144614

**Comment by villazon** [comment]
@vhotspur  I think I found the issue.  It's not reading the correct manifest. 

by printing: 
```
 System.out.println(MetaInfo.class.getResource("/META-INF/MANIFEST.MF"));
```
On JDK8, it returns: 
```
jar:file:/Library/Java/Extensions/RXTXcomm.jar!/META-INF/MANIFEST.MF
```
On JDK9, it correctly returns:
```
jar:file:/Users/alexvillazon/RENAISSANCE/renaissance-benchmarks/target/renaissance-0.9.0.jar!/META-INF/MANIFEST.MF
```
