### ISSUE TITLE
Contention on Spark benchmarks on machines with lots of CPUs

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#145]
Currently, our Spark benchmarks set the number of threads per executors to be equal to the number of available CPUs via `Runtime.getRuntime.availableProcessors`.

On machines with lots of CPUs, this value can be high (e.g. 64 or 128) and this has the consequence to create a lot of contention in the benchmark.
The ALS algorithm, used by `als` and `movie-lens` benchmarks, does a lot of data movement and if we have too many threads, the performance will degrade significantly.

See the (rounded) scores for `movie-lens` for different thread configuration in Spark on my 6 cores Macbook Pro. Note that the `Runtime.getRuntime.availableProcessors` returns 12 because of hyperthreading.

| thread count | score (ms) |
|---|---|
| 64 | 370000 |
| 24 | 42000 |
| 12 | 16300 |
| 5 | 9200 |
| 4 | 9400 |
| 3 | 8200 |
| 2 | 8400 |

The workload size **does not** depend on the thread count.

After a bit of research, it appears that we should not set the number of threads to such a high value. 5 is even suggested as an upper bound to maximise hadoop throughput in [1].

> HDFS Throughput: HDFS client has trouble with tons of concurrent threads. It was observed that HDFS achieves full write throughput with ~5 tasks per executor. So it’s good to keep the number of cores per executor below that number.

I would suggest that we fix the number of threads per executor to 3, 4 or 5 to still exercise parallelism as much as we can but without creating contention for Spark.

@ceresek, since you made some measurements, did you notice such behavior on big machines ?

[1] https://spoddutur.github.io/spark-notes/distribution_of_executors_cores_and_memory_for_spark_application.html

[2] https://db-blog.web.cern.ch/blog/luca-canali/2017-09-performance-analysis-cpu-intensive-workload-apache-spark

**Comment by axel22** [comment]
Did you confirm this with multiple VMs?

**Comment by farquet** [comment]
Yes, I see the problem on OpenJDK, AdoptOpenJDK, OracleJDK and GraalVM CE and EE. That's all the VMs I tried.

**Comment by farquet** [comment]
More generally, and related to #27, I would say that we should avoid dynamic values that are based on the platform whenever possible.
In the case of number of threads per executor in Spark, that looks reasonable to me to set it to a fixed value.

**Comment by axel22** [comment]
I agree that we should tailor the default on als and movie-lens given the contention.
It does not seem to be occurring on other Spark benchmarks, though, so my vote would be to keep the CPU-based thread count there.

**Comment by farquet** [comment]
Well, I think we should fix the number of threads for all Spark benchmarks and not only `als` and `movie-lens`. I notice contentions and performance degradation on all other Spark benchmarks too. It's not 25x different, but it ranges from 30% slowdown to 2x slowdown. So it creates at least little contention on all of them.

Moreover, we want this benchmark suite to be as close as possible from what a user application would look like and it is a common practice, for performance reasons, to keep this value below 5 (as we can see, it's a wise choice).

In any case, I think we should pick the value `4` because it is matching what is expected for real world application, is still reasonably parallel and would also match the number of cores on small laptops.

**Comment by farquet** [comment]
I'm happy to get more precise numbers for all Spark benchmarks, but independently of what the actual numbers are, **it is a bug** to set the number of threads to something so high and does not represent what an actual Spark workload looks like.

Indeed, a Spark app writer would scale the app by increasing the number of physical nodes and/or the number of executors per node, but won't go beyond 5 for the number of threads per executor because it doesn't give you more throughput and creates contention [1]. So what we are doing here is clearly wrong.

The solution proposed in that PR keeps a single executor and removes this bug. I would argue against the fact that using all cores as spark threads makes it a parallel benchmark, it only makes it a buggy benchmark since there is just a single executor anyway.

Another reasonable approach that would really make those benchmarks parallel using all the available cores would be to increase the number of executors (`spark.executor.instances`) and give each executors 2 to 4 threads.

Basically, the best way to maximize resource usage and throughput on a single Spark node would be to do something like : `NUM_THREADS * NUM_EXECUTORS = NUM_CORES - 1`.

`NUM_THREADS` could be different from a benchmark to another depending on how much data movement there is. So this could be fine tuned per benchmark and `NUM_EXECUTORS` would simply be computed based on `NUM_THREADS` and `NUM_CORES`. Maybe a max value could also be set.

I gave a quick try of that approach and I can get 9% better throughput for `page-rank` for instance if I fix 4 threads and 2 executors on my 6 cores macbook. However, `movie-lens` becomes much jumpier, probably because of data movement and maybe more GC. Nevertheless, some iterations give a better score than the best score achieved with the old setup.

Anyway, I don't want to dive too deep into this analysis now, but I think it is the way to go. My suggestion here would be to : 
1. Merge that PR as a bugfix to make the suite usable and correct on big machines
2. Do proper parallelism of Spark benchmarks in a subsequent PR. That would imply a deeper analysis of each better to find the good tradeoffs for each workload.

[1] https://stackoverflow.com/questions/24622108/apache-spark-the-number-of-cores-vs-the-number-of-executors
