### ISSUE TITLE
finagle-http not sending enough requests

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#148]
Looking at the following code in `benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala` it seems to me that `val response ...` should be moved to the inner loop as in the current setup we sent one request per client and repeatedly read its result. But the naming suggests that there should be `NUM_REQUESTS` requests sent.

Is this a bug or intentional behaviour?

```scala
override def run(): Unit = {
  val client: Service[http.Request, http.Response] =
    com.twitter.finagle.Http.newService(s"localhost:$port")
  val request = http.Request(http.Method.Get, "/json")
  request.host = s"localhost:$port"
  val response: Future[http.Response] = client(request) // <============
  for (i <- 0 until NUM_REQUESTS) {
    Await.result(response.onSuccess { rep: http.Response =>
      totalLength += rep.content.length
    })
  }
  client.close()
}
```

**Comment by axel22** [comment]
Indeed, this looks like a bug. We should rewrite that part.
