### ISSUE TITLE
finagle-http not parallel enough?

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#149]
Looking at the benchmark in `benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala` I wonder whether the `clientThread.join()` should not be in a separate loop as outlined below? That way the benchmark would spawn multiple (parallel) clients, let them work and wait for them in the end. Or is this intentional?

```scala
val listOfThreads = ...
for (i <- 0 until NUM_CLIENTS) {
  val clientThread = new Thread {
    ...
  clientThread.start()
  listOfThreads.append(clientThread)
}
for (i <- listOfThreads) {
  i.join()
}
```

**Comment by axel22** [comment]
I agree - most likely, the intent was to join outside of the loop.
