### ISSUE TITLE
Add Config parsing in the JMH build

### ISSUE THREAD

**Issue by axel22** [renaissance-benchmarks/renaissance#155]
Currently, it is not possible to pass Renaissance-specific command-line options to the **JMH-enabled build** of Renaissance, but only JMH-specific options.
For most current options, this does not make sense anyway, since current Renaissance options control how the harness executes the benchmark or select the benchmarks, which must be left to JMH anyway in the JMH-enabled build. The only current exception seems to be the `--functional-test` flag.
In the future, however, we will have benchmark-specific parametrization, so it will be necessary to pass in more options to Renaissance, through JMH. For this, we will need to find a way to:

1. Pass the Renaissance-specific options in when running JMH.
2. Make sure the `Config` object inside the `JmhRenaissanceBenchmark` class gets populated with the parsed Renaissance-specific options.
3. Maybe somehow disable the parsing of harness-specific options.

**Comment by lbulej** [comment]
Do we still need this, or can this be solved by using the `jmh` configurations?

**Comment by axel22** [comment]
I guess we only need this if we plan to support plugins.
But since the `jmh` configuration solves this use-case, I think we can close this.

**Comment by lbulej** [comment]
OK, I'll close this particular case as solved by #191 and let's see if a specific use-case pops.
