### ISSUE TITLE
Validation failure not stored in JSON/CSV

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#162]
When a benchmark (validation) fails, the JSON output is shorter (than in successful run) but the failure is not logged there. One has to inspect stdout for that information.

This information should be part of the JSON somehow (we already have `environment.vm.termination` field there).

Storing this inside CSV could be tricky, though.

**Comment by farquet** [comment]
what about error reporting when using the JMH harness ?
