### ISSUE TITLE
Core JAR included multiple times

### ISSUE THREAD

**Issue by axel22** [renaissance-benchmarks/renaissance#165]
Reported by @tkrodriguez : we have some of the dependencies JARs multiplied across different subprojects. This inflates the final JAR size a bit, but I think it's not an immediate cause for alarm.

```
2 leveldbjni-all-1.8.jar
2 aopalliance-1.0.jar
2 scala-reflect-2.11.8.jar
2 opencsv-2.3.jar
2 lz4-1.3.0.jar
2 paranamer-2.8.jar
2 javax.inject-1.jar
2 commons-compress-1.12.jar
2 scala-parser-combinators_2.11-1.0.4.jar
2 guava-19.0.jar
5 scala-library-2.12.8.jar
5 scala-library-2.11.8.jar
6 commons-io-2.6.jar
13 renaissance-core-0.9.0.jar 
```

Long-term, we should probably implement some sort of compression for JAR duplicates.

A more immediate action might be to figure out why we duplicate the `renaissance-core` library across projects. @vhotspur @lbulej Were you aware of this? Seems like we're including the core unnecessarily in the subproject JARs:

https://github.com/renaissance-benchmarks/renaissance/blob/master/build.sbt#L50

**Comment by lbulej** [comment]
As of #267 the `renaissance-core` library is considered a `provided` dependency and is not packaged at all, because its classes are provided directly by the top-level bundle. This does nothing about scala library classes though, but I'm closing this for now.
