### ISSUE TITLE
Failures in the oraclejdk11 installer

### ISSUE THREAD

**Issue by axel22** [renaissance-benchmarks/renaissance#167]
https://travis-ci.org/renaissance-benchmarks/renaissance/jobs/551964076

```
Installing oraclejdk11
$ export JAVA_HOME=~/oraclejdk11
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"
install-jdk.sh 2019-06-25
Variables:
  feature = 11
  license = BCL
       os = linux-x64
      url = http://download.oracle.com/otn-pub/java/jdk/11.0.3+12/37f5e150db5247ab9333b11c1dddcd30/jdk-11.0.3_linux-x64_bin.tar.gz
   status = 302
  archive = /home/travis/.cache/install-jdk/jdk-11.0.3_linux-x64_bin.tar.gz
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/11.0.3+12/37f5e150db5247ab9333b11c1dddcd30/jdk-11.0.3_linux-x64_bin.tar.gz...
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"" failed and exited with 8 during .
```

**Comment by vhotspur** [comment]
I was hoping it will get fixed automagically but it is (again) no longer possible to download the JDK in headless manner :-(. Will probably need to drop support for this JDK altogether or rewrite configuration to use the JDK switcher manually.

See [this thread](https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892) and also [this one](https://travis-ci.community/t/install-of-oraclejdk11-is-failing-11-0-3-12/3887). Upstream issue is [here](https://github.com/sormuras/bach/issues/56).

**Comment by gilles-duboscq** [comment]
You can probably switch to using `openjdk11` instead of `oraclejdk11`
