### ISSUE TITLE
dotty benchmark fails on Windows

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#176]
Running `dotty` benchmark on Windows results in the following failure (see [also here](https://ci.appveyor.com/project/vhotspur/renaissance/builds/25722034#L694) a build from AppVeyor (PR #139)):

```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/user/renaissance/./tmp-jars-76485191019216267
05/cp-scala-dotty_2.12-0.9.0.jar5631486227090191329.jar                                                                         
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)                                                   
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)                                                       
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)                                                        
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)                                                                    
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)                                                     
        at java.nio.file.Paths.get(Paths.java:84)                                                                               
        at dotty.tools.io.Directory$.apply(Directory.scala:30)  
        ...
```

For context, we run the compiler with the following arguments:

```scala
    val args = Seq[String](
      DOTTY_ARG_CLASS_PATH,
      Thread.currentThread.getContextClassLoader
        .asInstanceOf[URLClassLoader]
        .getURLs
        .mkString(File.pathSeparator),
      DOTTY_ARG_TYPE_CONVERSION,
      DOTTY_ARG_CLASS_FILE_DESTINATION,
      outputPath.toString
    )
```

The culprit seems to be that in the end we pass list of URLs that are preceded by `file:/` that the Windows part of FS abstraction is unable to handle. Note that the harness installed this context class loader so we know that the classpath points always to a list of JARs stored on disk.

It seems that the following fixes it (it still runs on Linux and it also runs on Windows). But that is a rather fragile solution. I do not know Dotty at all so I am wondering why it cannot use the existing classpath or whether it would be possible to give it some classloader directly instead of this remarshalling.

Any opinions what to do with this (especially whether we should merge such workaround at all)?

```diff
--- a/benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
+++ b/benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
@@ -85,6 +85,7 @@ class Dotty extends RenaissanceBenchmark {
       Thread.currentThread.getContextClassLoader
         .asInstanceOf[URLClassLoader]
         .getURLs
+        .map(p => p.toString.replace("file:/", ""))
         .mkString(File.pathSeparator),
       DOTTY_ARG_TYPE_CONVERSION,
       DOTTY_ARG_CLASS_FILE_DESTINATION,
```

**Comment by farquet** [comment]
That would be great if  @smarter , who is involved in Dotty development could shed some light on the classloading questions.

**Comment by smarter** [comment]
>  I do not know Dotty at all so I am wondering why it cannot use the existing classpath or whether it would be possible to give it some classloader directly instead of this remarshalling.

Yes, if you just need to expose the JVM classpath to the compiler, you can pass the flag `-usejavacp` to the compiler (so here that would mean replacing the first two elements of args by `"-usejavacp"`).

**Comment by vhotspur** [comment]
Thanks for the suggestion, @smarter. It was the pointer I needed but I found that this switch means Dotty would look into the top-most classloader (use path from `java.class.path`) which is, unfortunately, not the best solution for us. We do not want to pollute from individual benchmarks the main classpath. 

So in the end I converted the URLs to local paths in PR #183.
