### ISSUE TITLE
Specify plugin class inside plugin JAR

### ISSUE THREAD

**Issue by vhotspur** [renaissance-benchmarks/renaissance#194]
When creating and using a plugin, it is added to the command-line via

```shell
--plugin "path-to-plugin.jar:other-deps.jar!org.package.ClassWithPlugin"
```

which can get quite long to type (and shell offers no completion for the classname). Furthermore, the exclamation mark has a special meaning inside shell when not escaped.

We should either abuse `Main-Class` to store the main class of the plugin or add some other field to `MANIFEST.MF` inside the plugin JAR that could be picked automatically by the extension loader.

**Comment by lbulej** [comment]
I think that we could agree on looking for `Renaissance-Plugin` attribute in the JAR manifests when the plugin specifier does not contain any `!`. I would avoid abusing `Main-Class`.

Even though we (me and @vhotspur ) have previously discussed the option of having some plugins packaged with the harness (and activating them just by using the class name, also without `!`), I think that it is not really needed that much -- if there is (optional) functionality that we think is worth including with the harness, we should just activate it with a separate CLI option.
