### ISSUE TITLE
Benchmark failure under JMH harness does not fail the build in Travis

### ISSUE THREAD

**Issue by lbulej** [renaissance-benchmarks/renaissance#199]
See the [output](https://travis-ci.org/renaissance-benchmarks/renaissance/jobs/578840659) of job #357.10 where the benchmark fails on line [246](https://travis-ci.org/renaissance-benchmarks/renaissance/jobs/578840659#L246), but is still considered success on line [277](https://travis-ci.org/renaissance-benchmarks/renaissance/jobs/578840659#L277).

**Comment by vhotspur** [comment]
PR #200 should fix that.

**Comment by lbulej** [comment]
It indeed does, thanks!
