### ISSUE TITLE
Built on tag v0.10.0 get renaissance-gpl-0.9.0.jar/renaissance-jmh-assembly-0.9.0.jar ?

### ISSUE THREAD

**Issue by feng-qi** [renaissance-benchmarks/renaissance#206]
I cloned this repo and check out tag `v0.10.0`. After the commands `tools/sbt/bin/sbt assembly` and `tools/sbt/bin/sbt renaissanceJmh/jmh:assembly`, I get `renaissance-gpl-0.9.0.jar` / `renaissance-jmh-assembly-0.9.0.jar`.

Shouldn't I get `renaissance-gpl-0.10.0.jar`/`renaissance-jmh-assembly-0.10.0.jar`?

**Comment by farquet** [comment]
The tag was pointing to a commit before the version string bump, so you are actually running `0.10.0` but it is misnamed.

I've just updated the tag, so this should be fixed now.

Thanks @feng-qi for the report !
