### ISSUE TITLE
dotty and finagle-chirper tests fail using Oracle JDK 8u231 on W10 Pro 1909

### ISSUE THREAD

**Issue by dcominottim** [renaissance-benchmarks/renaissance#208]
![Screenshot (297)](https://user-images.githubusercontent.com/4914233/69903910-8e27c700-137e-11ea-970c-49a5b2046dfb.png)
![Screenshot (298)](https://user-images.githubusercontent.com/4914233/69903912-8e27c700-137e-11ea-84cc-1ea6a4434a74.png)
![Screenshot (299)](https://user-images.githubusercontent.com/4914233/69903913-8ec05d80-137e-11ea-8605-2d5ce10ff26f.png)

**Comment by axel22** [comment]
Thanks for reporting!
It seems that these are problems with the path names on Windows.

**Comment by dcominottim** [comment]
Thanks! `dotty` seems to run fine with the latest code from `master` but `finagle-chirper` is still giving the same error.

**Comment by farquet** [comment]
This issue has also been reported in #211. Since the error is easier to read there, let's close this issue and follow the progress in #211.
