### ISSUE TITLE
Does not build out of the box

### ISSUE THREAD

**Issue by RobertHenry6bev** [renaissance-benchmarks/renaissance#219]
I'm on ubuntu 19.10, using OpenJDK Runtime Environment (build 14-ea+18-Ubuntu-1)

Running tools/sbt/bin/sbt assembly per renaissance instructions downloads sbt 1.2.8.  After a while, there's an uncaught exception 
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
.......
[error] Caused by: java.lang.RuntimeException: /packages cannot be represented as URI

Googling the error message ends up at https://github.com/scala/bug/issues/11381 where one commentator says to use sbt 1.3.2

Should I (and you) somehow change to sbt 1.3.2, or is there a simpler fix?

**Comment by vhotspur** [comment]
Hello, thanks for the report. We are aware of this issue a bit (e.g. #213) but we have not yet prepared a fix.

BTW, simple updating SBT did not work for me as it broke other dependencies (we use 4 different Scala versions across the suite which does not simplify things).

**Comment by farquet** [comment]
@lbulej is it solved with the recent sbt upgrade?

**Comment by farquet** [comment]
Ok. I'm closing. If anyone faces that issue again, feel free to re-open.
