### ISSUE TITLE
log-regression benchmark doesn't cache its RDD

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#226]
All Spark benchmarks are structured the same way and start by loading data from files, then transform it in an RDD and then run the benchmark on the cached RDD.
However, the `log-regression` benchmark doesn't cache its RDD, recomputing it during the iteration of the benchmarks. This is an inconsistency and a problem we have to fix.

Credit goes to @tkrodriguez for spotting the issue.

```
diff --git a/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala b/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
index ee5daad..0fefa91 100644
--- a/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
+++ b/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
@@ -96,7 +96,7 @@ final class LogRegression extends Benchmark with SparkUtil {
           features(index) = value
         }
         (parts(0).toDouble, Vectors.dense(features))
-      }
+      }.cache();
   }
 
   override def setUpBeforeAll(c: BenchmarkContext): Unit = {
```

**Comment by lbulej** [comment]
I checked other Spark benchmarks, they seem to be fine. `dec-tree` does not use any RDDs, but there seems to be a problem with `movie-lens`, see #227.

**Comment by lbulej** [comment]
> I checked other Spark benchmarks, they seem to be fine. `dec-tree` does not use any RDDs, but there seems to be a problem with `movie-lens`, see #227.

Correction, `dec-tree` uses `DataFrame`, as @farquet found out when working on #228.
