### ISSUE TITLE
[question] Scala compiler used in the benchmark suite

### ISSUE THREAD

**Issue by underhood31** [renaissance-benchmarks/renaissance#245]
Hi! 
Is the scala compiler used while building the suite is included in the benchmark repository (and where) or does it uses the one installed in the system.

**Comment by axel22** [comment]
It uses the compiler version that the sbt build definition tells it to. In fact, separate benchmarks use different Scala versions, and each of them gets compiled with the respective version of the Scala compiler.

**Comment by underhood31** [comment]
For learning purpose I want to change the scala compiler for a benchmark, how can I do that?

**Comment by lbulej** [comment]
Each sub-project in the `benchmarks` directory has its own `build.sbt` file, which contains the `scalaVersion` setting. This tells you what Scala version is being used and you can try changing it for that sub-project.

Just be advised that changing Scala version may cause a benchmark to fail to compile, especially if you change major versions -- some dependencies simply don't exist for some major Scala releases. The `master` branch currently uses two Scala versions, 2.12.13 and 2.13.5. There is no plan to go back to older versions, especially with Scala 3 around the corner.

**Comment by underhood31** [comment]
Thanks for replying.
I am new to programming with scala please correct me if I am wrong,

If every benchmark uses a different version of scala then the binaries of all those versions should be present in the benchmark suite, but I am unable to find their location. Where are they stored?

**Comment by underhood31** [comment]
Or are the dependencies downloaded at the build time?

**Comment by lbulej** [comment]
> Or are the dependencies downloaded at the build time?

Yes. The build tool downloads the right Scala version and the build system bundles the corresponding Scala library into the final jar file. If you change the Scala version in the `build.sbt` file of a benchmark sub-project and actually succeed compiling it, then that benchmark will use a different Scala library.

**Comment by underhood31** [comment]
Thanks, I understood it. 

But for a research project, I will change the code of the scala standard library and I want to use that modified version to run some benchmarks in this suite. Is this possible?

**Comment by lbulej** [comment]
Probably the simplest way is to replace the Scala library in the final Renaissance JAR (and it can be easily scripted).

I don't know of a simple way to tell the build tool to use a modified Scala library. You could try disabling the `autoScalaLibrary` setting and provide the modified Scala library as an explicit dependency, but SBT might (strongly) resist your efforts.

**Comment by underhood31** [comment]
Thanks this was very helpful!
