### ISSUE TITLE
Renaissance uses old slf4j version that ships a vulnerable log4j version

### ISSUE THREAD

**Issue by parttimenerd** [renaissance-benchmarks/renaissance#365]
The currently used slf4j version 1.7.33 uses a vulnerable log4j version, see https://www.slf4j.org/news.html.
This is problematic when running renaissance on servers in our intranet (and leads many security scanners to flag our renaissance instance as problematic).

**Comment by ArnoZeller** [comment]
It would be great if there will be a new release for this. (i.e. 0.14.2).

**Comment by vhotspur** [comment]
> It would be great if there will be a new release for this. (i.e. 0.14.2).

@lbulej What are the plans for next release, please?

**Comment by lbulej** [comment]
I'm fine with this small update, otherwise I would be going for 0.15 with component updates all over the board (Spark, Scala, ...) and I would not want to rush that. I'll check that we don't pull in log4j anymore and will do a release sometime next week.
