### ISSUE TITLE
Can we sync with the jna community to support the LoongArch architecture?

### ISSUE THREAD

**Issue by Panxuefeng-loongson** [renaissance-benchmarks/renaissance#369]
Hi all,

I am a developer from Loongson. LoongArch is a risc architecture developed by Loongson. Renaissance is an authoritative benchmark, we use it to improve the quality of the Loongson platform JDK, but the jna package supporting LoongArch is missing in renaissance, here is the contents of jna unpacked in renaissance:
```
loongson@loongson-pc:~/下载/shared/temp/com/sun/jna$ ls linux-
linux-aarch64/  linux-arm/      linux-armel/    linux-mips64el/ linux-ppc/    
linux-ppc64le/  linux-riscv64/  linux-s390x/    linux-x86/      linux-x86-64/
```
Now that LoongArch is supported by the jna community: https://github.com/java-native-access/jna/pull/1440, can we sync it so that LoongArch users can also use renaissance easily?

Thanks

**Comment by Panxuefeng-loongson** [comment]
I am glad to receive your reply. Bumping JNA to version 5.12.1 will solve the problem. I'm looking forward to supporting LoongArch's renaissance.

**Comment by Panxuefeng-loongson** [comment]
> > I am glad to receive your reply. Bumping JNA to version 5.12.1 will solve the problem. I'm looking forward to supporting LoongArch's renaissance.
> 
> Renaissance now uses JNA 5.12.1 (see release 0.14.2), so I hope that it fixes the problem.

Good news to me, thanks

**Comment by lbulej** [comment]
I'm assuming the update fixed the problem. Please reopen if necessary.
