### ISSUE TITLE
Renaissance benchmark for riscv

### ISSUE THREAD

**Issue by urniming** [renaissance-benchmarks/renaissance#390]
Hi
I'm glad to have such a good basic test
However, I encountered the following problem when running apache-spark tests on the riscv platform

- arch rv64imafdcvsu
- JDK-Version: OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.19.15+7-GA (11.0.19.15+7, mixed mode, tiered, compressed oops, g1 gc, linux-riscv64)
- command line:  time java -Xms4g -Xmx4g -jar  'renaissance-gpl-0.14.2.jar' chi-square

![image](https://github.com/renaissance-benchmarks/renaissance/assets/130720170/ef9cc1e1-58d0-4639-949d-6de97f47e032)
In addition to chi-square, the apache-spark benchmark als gauss-mix also has fatal-error, but on the x86 platform, it runs very well, so someone can help determine what is the problem

**Comment by davleopo** [comment]
@urniming  thanks for the report.

However, what you are seeing here is most likely actual bugs of the running VM and not the benchmark itself. The hs_err screenshot you shared fails in gc code for example.
You should report these bugs upstream at the respective jdk project.

**Comment by urniming** [comment]
> @urniming thanks for the report.
> 
> However, what you are seeing here is most likely actual bugs of the running VM and not the benchmark itself. The hs_err screenshot you shared fails in gc code for example. You should report these bugs upstream at the respective jdk project.

OK,Thanks ！

**Comment by davleopo** [comment]
Ill close this for now then - if you have further problems with renaissance please do not hesitate to report them here again. Thank you!
