### ISSUE TITLE
Specify parameters for perfAsm

### ISSUE THREAD

**Issue by BrytonLee** [renaissance-benchmarks/renaissance#429]
Hi,

Is there any approach to specfiy parameters for perfAsm profiler? For example, I want to change hottest method threshold from default 10% to  5%,  is there any option in commandline?

Thanks in advance.

**Comment by lbulej** [comment]
Pardon my ignorance, but how is that done with other JMH benchmarks integrating perfAsm?

In the JMH-enabled bundle the command line is completely handled by JMH &mdash; I would assume that what works for other JMH benchmarks could work here?

**Comment by BrytonLee** [comment]
Sorry for bothering you guys, I realised that I was in a wrong way to specify parameter for `perfasm`.  The correct way is `-prof perfasm:<param=?>`. In my case, it is `-prof perfasm:hotThreshold=0.05`.
