### ISSUE TITLE
Project listing should be more robust

### ISSUE THREAD

**Issue by farquet** [renaissance-benchmarks/renaissance#64]
If you are a Mac user and you browse with the Finder until the `benchmarks` directory, the OS will create an hidden directory there. While loading the project, this hidden directory will be considered as a subproject and this will crash early with something like :
```
[error] Invalid build URI (no handler available): file:<path>/renaissance-benchmarks/benchmarks/.DS_Store/
```
While it's easy to exclude it, we should make the project listing more robust. Maybe only consider directories that contain a `build.sbt` file and ignore the rest.

**Comment by lbulej** [comment]
Fixed in #108
