### ISSUE TITLE
Better error handling in neo4j-analytics

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#83]
When terminating neo4j-analytics by killing its threads (necessary when the harness does not have support for execution timeout), the benchmark can reach a state where the database is shut down, accesses report `org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.` but the benchmark happily reports nonsensical repetition times (from 5-6 seconds per repetition to sub ms per repetition).

The benchmark should not report repetition times when the repetitions are obviously failing. We should check this for all benchmarks (that is, include result validation and report at least a warning if the results do not validate).

[neo4j-analytics-stderr.log](https://github.com/D-iii-S/renaissance-benchmarks/files/3124704/neo4j-analytics-stderr.log)
[neo4j-analytics-stdout.log](https://github.com/D-iii-S/renaissance-benchmarks/files/3124705/neo4j-analytics-stdout.log)

**Comment by farquet** [comment]
Fixed in #224.
